Добавлена функциональность тз №6
rabarcre/java-kanban pull request #1
Opened 2024-07-19 01:31 UTC by rabarcre

2024-07-19 21:05 UTC, sergeymamonov requested changes
Давайте более информативные названия каждому коммиту. Ведь в каждом конкретном коммите вы делали что-то, а то получается десяток коммитов с одним и тем же названием. 
main.manager.InMemoryTaskManager#updateEpicStatus - будет ли обновляться статус эпика при удалении подзадачи?
main.task.Subtask#epicId может добавить модификатор доступа?

2024-07-19 21:05 UTC, sergeymamonov commented on src/main/manager/InMemoryHistoryManager.java
> +        Node head;
Можно дать модификатор доступа этим полям?

2024-07-19 21:05 UTC, sergeymamonov commented on src/main/manager/InMemoryHistoryManager.java
> +    CusLinkedList history = new CusLinkedList();
Этим полям можно дать модификатор доступа?

2024-07-19 21:05 UTC, sergeymamonov commented on src/main/manager/TaskManager.java
>      boolean isDeletedTask(int taskId);
Странный метод. Если мы хотим что-то удалить, то нужно сделать явный метод для удаления. Если мы хотим что-то проверить, то это метод должен быть идемпотентным. И сколько бы мы его не вызывали, он бы делал одно и то же. Причем такой метод не должен ничего менять. Пример для массива isEmpty(). А здесь метод, который ожидаешь что делает только проверку, на самом деле удаляет. Причем если вызвать второй раз, что будет? Равен ли второй ответ первому ответу?

2024-07-19 21:05 UTC, sergeymamonov commented on src/main/task/Subtask.java
> +        return "Subtask";
Тип лучше сделать энамом.

2024-07-26 00:20 UTC, rabarcre commented on src/main/manager/TaskManager.java
>      boolean isDeletedTask(int taskId);
Согласен, что метод странный. Просто хотелось, чтобы возвращался true если удаление прошло успешно, это не было изначально проверочным методом. Лучше от этого отказаться или есть какой - то другой способ?

2024-07-26 03:51 UTC, sergeymamonov commented on src/main/manager/InMemoryHistoryManager.java
> +    static int id = 0;
Лучше добавить модификатор доступа и сделать поля экземпляром класса, а не статическим.

2024-07-26 03:51 UTC, sergeymamonov commented on src/main/manager/TaskManager.java
>      boolean isDeletedTask(int taskId);
Не часто я видел, чтобы метод удаления возвращал логический ответ. Обычно возвращает удаляемый объект или вообще ничего. А делать обертку на методом delete не нужно.

2024-07-26 03:52 UTC, sergeymamonov approved these changes

2024-08-12 09:47 UTC, merged