Sprint 7 solution in file manager
rabarcre/java-kanban pull request #2
Opened 2024-08-15 02:19 UTC by rabarcre

2024-08-15 22:34 UTC, sergeymamonov requested changes

2024-08-15 22:34 UTC, sergeymamonov commented on src/main/formatter/CSVFormatter.java
> +    public static String getHeader() {
Лучше сделать не как геттер для строки, а как константу эту строку.

2024-08-15 22:34 UTC, sergeymamonov commented on src/main/manager/InMemoryTaskManager.java
> +    protected final Map<Integer, Task> tasks = new HashMap<>();
Лучше обращаться из других классов к этим полям через геттеры.

2024-08-15 22:34 UTC, sergeymamonov commented on src/main/task/Subtask.java
> +        this.epicId = epicId;
Разберитесь, что значит this и почему это присвоение ничего не дает.

2024-08-15 22:34 UTC, sergeymamonov commented on src/main/task/Subtask.java
>      public Enum getTaskType() {
Здесь нужно возвращать TaskType, а не Enum.

2024-08-15 22:34 UTC, sergeymamonov commented on src/main/task/TaskType.java
>      Task,
Перечисления делают заглавными буквами.

2024-08-15 22:34 UTC, sergeymamonov commented on test/main/manager/FileBackedTaskManagerTest.java
> +import main.task.*;
Не используйте импорт через звездочку.

2024-08-16 02:41 UTC, rabarcre commented on src/main/task/Subtask.java
> +        this.epicId = epicId;
Да я скопировал конструктор снизу и что-то забыл удалить эту строку. Спасибо

2024-08-17 18:45 UTC, sergeymamonov approved these changes

2024-08-17 18:45 UTC, sergeymamonov commented on src/main/formatter/CSVFormatter.java
> +import main.task.*;
Не используйте импорт через звездочку.

2024-08-17 18:45 UTC, sergeymamonov commented on test/main/manager/FileBackedTaskManagerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Аналогично.

2024-08-20 21:28 UTC, merged